services:
  tasks-api:
    container_name: tasks-api
    depends_on:
      - sqlserver
    build: ./Miotto.Tasks/
    ports:
      - 8080:80
      - 8081:443
    environment:
      ASPNETCORE_ENVIRONMENT: Docker

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 5533:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "tasks@123"