services:
  tasks-api:
    container_name: tasks-api
    depends_on:
      - sqlserver
    build: ./src
    ports:
      - 8080
      - 8081
    environment:
      ASPNETCORE_ENVIRONMENT: Docker

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1434:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: tasks@123